"""empty message

Revision ID: e763cfd3a1b3
Revises: f69e74658a54
Create Date: 2018-08-31 11:51:22.148212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e763cfd3a1b3'
down_revision = 'f69e74658a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'menu_date')
    # ### end Alembic commands ###
